Comunication with Vifcon
nemocrys/multilog pull request #52
Opened 2024-07-15 12:36 UTC by Felix-Oesterle-IKZ

2024-07-25 15:25 UTC, kdadzis commented
@Felix-Oesterle-IKZ die aktuelle Umsetzung mit automatisch numerierten Ports bei NEMO Achsen ist viel zu fehleranfällig. Bitte die Config anpassen, dass für jede Achse der Port in der Config separat definiert wird.

@tsiapkinis bitte diese Anpassung unabhängig testen

2024-07-29 08:51 UTC, tsiapkinis requested changes
- Warum ist die config_template.yml gelöscht? Bitte eine aktuelle hinzufügen.
- Port Nummerierung für die Achsen anpassen (Siehe Kommentar von Kaspars)
- Rest sieht gut aus!

2024-08-07 11:13 UTC, tsiapkinis approved these changes
Looks good

2024-08-07 11:15 UTC, tsiapkinis approved these changes
Looks good. Latest working config_template added. Vifcon settings at the bottom.

2024-08-07 11:17 UTC, tsiapkinis commented
Added communication with vifcon devices via TCP.

2024-08-07 11:18 UTC, merged